// LOGIIINNNNNN

import { Inter } from "next/font/google";
import Homecss from "./Homcss/home.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sistema oficial Xander",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es"> {/* Definir el idioma de la página */}
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        {/* Cargar las fuentes de Google */}
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href={inter.url} rel="stylesheet" />
        {/* Cargar los estilos CSS */}
        <link rel="stylesheet" href={Homecss} />
      </head>
      <body className={inter.className}> {/* Aplicar la clase de la fuente */}
        {children}
      </body>
    </html>
  );
}
